// <auto-generated />
using System;
using BIBLIOTECA.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BIBLIOTECA.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    [Migration("20181111222632_quinto")]
    partial class quinto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BIBLIOTECA.Models.Bibliotecario", b =>
                {
                    b.Property<int>("id_bib")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("contraseña")
                        .IsRequired();

                    b.Property<string>("usuario")
                        .IsRequired();

                    b.HasKey("id_bib");

                    b.ToTable("bibliotecarios");
                });

            modelBuilder.Entity("BIBLIOTECA.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new { Id = 1, Nombre = "Sistemas" },
                        new { Id = 2, Nombre = "Arquitectura" },
                        new { Id = 3, Nombre = "Industrial" },
                        new { Id = 4, Nombre = "Matematica" }
                    );
                });

            modelBuilder.Entity("BIBLIOTECA.Models.Estudiante", b =>
                {
                    b.Property<int>("cod_est")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ape");

                    b.Property<string>("escuela");

                    b.Property<string>("nomb");

                    b.HasKey("cod_est");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("BIBLIOTECA.Models.Libro", b =>
                {
                    b.Property<int>("cod_lib")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CategoriaId");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(17);

                    b.Property<string>("autor")
                        .IsRequired();

                    b.Property<int>("año_pub");

                    b.Property<string>("editorial")
                        .IsRequired();

                    b.Property<string>("titulo")
                        .IsRequired();

                    b.HasKey("cod_lib");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("BIBLIOTECA.Models.Prestamo", b =>
                {
                    b.Property<int>("cod_prest")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Estudianteape");

                    b.Property<int?>("Estudiantecod_est");

                    b.Property<string>("Estudianteescuela");

                    b.Property<string>("Estudiantenomb");

                    b.Property<string>("LibroISBN");

                    b.Property<string>("Libroautor");

                    b.Property<int?>("Librocod_lib");

                    b.Property<string>("Librotitulo");

                    b.Property<int?>("ModalidadId")
                        .IsRequired();

                    b.Property<DateTime>("fecha_reserva");

                    b.HasKey("cod_prest");

                    b.HasIndex("Estudiantecod_est");

                    b.HasIndex("Librocod_lib");

                    b.HasIndex("ModalidadId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("ProyBibFinalCopia.Models.Modalidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Modalidades");

                    b.HasData(
                        new { Id = 1, Nombre = "A domicilio(max 2 dias)" },
                        new { Id = 2, Nombre = "A sala (hasta que cierre la biblioteca)" }
                    );
                });

            modelBuilder.Entity("BIBLIOTECA.Models.Libro", b =>
                {
                    b.HasOne("BIBLIOTECA.Models.Categoria", "Categoria")
                        .WithMany("Libros")
                        .HasForeignKey("CategoriaId");
                });

            modelBuilder.Entity("BIBLIOTECA.Models.Prestamo", b =>
                {
                    b.HasOne("BIBLIOTECA.Models.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("Estudiantecod_est");

                    b.HasOne("BIBLIOTECA.Models.Libro", "Libro")
                        .WithMany()
                        .HasForeignKey("Librocod_lib");

                    b.HasOne("ProyBibFinalCopia.Models.Modalidad", "Modalidad")
                        .WithMany("Prestamo")
                        .HasForeignKey("ModalidadId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
